SELECT CAST(CONCAT_WS("-",y,m,13) AS DATE) AS date
FROM (
        SELECT 2012 AS y
  UNION SELECT 2013
  UNION SELECT 2014
  UNION SELECT 2015
  UNION SELECT 2016
  UNION SELECT 2017
  UNION SELECT 2018
  UNION SELECT 2019
  UNION SELECT 2020 ) AS yseq
CROSS JOIN (
        SELECT 1 AS m
  UNION SELECT 2
  UNION SELECT 3
  UNION SELECT 4
  UNION SELECT 5
  UNION SELECT 6
  UNION SELECT 7
  UNION SELECT 8
  UNION SELECT 9
  UNION SELECT 10
  UNION SELECT 11
  UNION SELECT 12 ) AS mseq
GROUP BY date
HAVING DAYOFWEEK(date) = 6
ORDER BY date
